// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// Export file: exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: DJTest

	[behaviac.GeneratedTypeMetaInfo()]
	class Wait_bt_DJTest_node1 : behaviac.Wait
	{
		public Wait_bt_DJTest_node1()
		{
		}
		protected override double GetTime(Agent pAgent)
		{
			return 1000f;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_DJTest_node2 : behaviac.Action
	{
		public Action_bt_DJTest_node2()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
			method_p0 = -10;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.Agent pAgent_method = behaviac.Utils.GetParentAgent(pAgent, "DJTest");
			Debug.Check(pAgent_method != null || Utils.IsStaticClass("DJTest"));
			((DJTest)pAgent_method).ChangeHp(method_p0);
			return EBTStatus.BT_SUCCESS;
		}
		int method_p0;
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_DJTest_node4 : behaviac.Condition
	{
		public Condition_bt_DJTest_node4()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.Agent pAgent_opl = behaviac.Utils.GetParentAgent(pAgent, "DJTest");
			Debug.Check(pAgent_opl != null || Utils.IsStaticClass("DJTest"));
			bool opl = ((DJTest)pAgent_opl).isDead;
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_DJTest_node7 : behaviac.Action
	{
		public Action_bt_DJTest_node7()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.Agent pAgent_method = behaviac.Utils.GetParentAgent(pAgent, "DJTest");
			Debug.Check(pAgent_method != null || Utils.IsStaticClass("DJTest"));
			((DJTest)pAgent_method).ReBorn();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_DJTest_node8 : behaviac.Action
	{
		public Action_bt_DJTest_node8()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
			method_p0 = "TestUI";
			method_p1 = "nodeClick";
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.Agent pAgent_method = behaviac.Utils.GetParentAgent(pAgent, "DJTest");
			Debug.Check(pAgent_method != null || Utils.IsStaticClass("DJTest"));
			((DJTest)pAgent_method).ExecuteLua(method_p0, method_p1);
			return EBTStatus.BT_SUCCESS;
		}
		string method_p0;
		string method_p1;
	}

	public static class bt_DJTest
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("DJTest");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("DJTest");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("DJTest");
#endif
				bt.AddChild(node0);
				{
					Wait_bt_DJTest_node1 node1 = new Wait_bt_DJTest_node1();
					node1.SetClassNameString("Wait");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("DJTest");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Action_bt_DJTest_node2 node2 = new Action_bt_DJTest_node2();
					node2.SetClassNameString("Action");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("DJTest");
#endif
					node0.AddChild(node2);
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					IfElse node3 = new IfElse();
					node3.SetClassNameString("IfElse");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("DJTest");
#endif
					node0.AddChild(node3);
					{
						Condition_bt_DJTest_node4 node4 = new Condition_bt_DJTest_node4();
						node4.SetClassNameString("Condition");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("DJTest");
#endif
						node3.AddChild(node4);
						node3.SetHasEvents(node3.HasEvents() | node4.HasEvents());
					}
					{
						Sequence node5 = new Sequence();
						node5.SetClassNameString("Sequence");
						node5.SetId(5);
#if !BEHAVIAC_RELEASE
						node5.SetAgentType("DJTest");
#endif
						node3.AddChild(node5);
						{
							Action_bt_DJTest_node7 node7 = new Action_bt_DJTest_node7();
							node7.SetClassNameString("Action");
							node7.SetId(7);
#if !BEHAVIAC_RELEASE
							node7.SetAgentType("DJTest");
#endif
							node5.AddChild(node7);
							node5.SetHasEvents(node5.HasEvents() | node7.HasEvents());
						}
						{
							Action_bt_DJTest_node8 node8 = new Action_bt_DJTest_node8();
							node8.SetClassNameString("Action");
							node8.SetId(8);
#if !BEHAVIAC_RELEASE
							node8.SetAgentType("DJTest");
#endif
							node5.AddChild(node8);
							node5.SetHasEvents(node5.HasEvents() | node8.HasEvents());
						}
						node3.SetHasEvents(node3.HasEvents() | node5.HasEvents());
					}
					{
						Noop node6 = new Noop();
						node6.SetClassNameString("Noop");
						node6.SetId(6);
#if !BEHAVIAC_RELEASE
						node6.SetAgentType("DJTest");
#endif
						node3.AddChild(node6);
						node3.SetHasEvents(node3.HasEvents() | node6.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
